Initial commit of fully working script
Implemented commands: 'add', 'move', 'update', 'remove'

diff --git a/git-drupal b/git-drupal
--- a/git-drupal
+++ b/git-drupal
@@ -11,6 +11,7 @@ PATH=$PATH:$(git --exec-path)
 source git-sh-setup
 
 require_work_tree
+require_clean_work_tree
 
 if [ $# -eq 0 ]; then
 	set -- -h
@@ -25,6 +26,7 @@ git drupal update <extension> <version>
 --
 h,help            show help
 P,prefix=         name of subdirectory where extensions are stored
+  options for 'add', 'move', 'remove', 'update'
 m,message=        use the given message as the commit message for the merge commit
 "
 eval "$(echo "$OPTS_SPEC" | git rev-parse --parseopt -- "$@" || echo exit $?)"
@@ -32,6 +34,7 @@ eval "$(echo "$OPTS_SPEC" | git rev-parse --parseopt -- "$@" || echo exit $?)"
 requirements(){
 	local cmd=(
 		curl
+		tar
 		wget
 	)
 
@@ -41,7 +44,6 @@ requirements(){
 		fi
 	done
 }
-requirements
 
 # Require to run a command from the toplevel of GIT repository.
 if [ "$(git rev-parse --show-toplevel)" != "$PWD" ]; then
@@ -56,7 +58,9 @@ while [ $# -gt 0 ]; do
 	opt="$1"
 	shift
 	case "$opt" in
-		-P) prefix="$1"; shift ;;
+		-P) prefix="$1";
+				# Trim trailing slash.
+				eval prefix="$(echo "$prefix" | sed 's/\/$//')"; shift ;;
 		-m) message="$1"; shift ;;
 		--) break ;;
 		*) die "Unexpected option: $opt" ;;
@@ -71,7 +75,7 @@ case "$command" in
 esac
 
 # Require prefix for commands.
-if [ "$command" = "add" -o "$command" = "move" ]; then
+if [ "$command" == "add" -o "$command" == "move" ]; then
 	if [ -z "$prefix" ]; then
 		die "You must provide the --prefix option."
 	fi
@@ -92,25 +96,29 @@ http="https://www.drupal.org/project"
 # The extension name must start with a letter and contains only of lowercase
 # letters, digits and underscores.
 # See Drupal docs: https://www.drupal.org/node/1074362
-if [[ "$1" =~ ^([a-z][a-z0-9\_]{0,}[^_])$ ]]; then
-	EXTENSION="$1"
-else
-	die "${extension_type^} name MUST start with a letter and contain only of lowercase letters, digits and underscores."
-fi
+drupal_extension_name_validate() {
+	if [[ "$1" =~ ^([a-z][a-z0-9\_]{0,}[^_])$ ]]; then
+		EXTENSION="$1"
+	else
+		die "${extension_type^} name MUST start with a letter and contain only of lowercase letters, digits and underscores."
+	fi
+}
 
 # Validate extension (module/theme) version.
 # The extension version must start with a digit [3-9] (Drupal GIT repository has
 # no releases under 3.x: http://cgit.drupalcode.org/drupal/refs).
 # See Drupal docs: https://www.drupal.org/node/1015226
-if [[ "$2" =~ ^[3-9].* ]]; then
-	VERSION="$2"
-else
-	die "${extension_type^} version MUST start with a digit [3-9]."
-fi
+drupal_extension_version_validate() {
+	if [[ "$1" =~ ^[3-9].* ]]; then
+		VERSION="$1"
+	else
+		die "${extension_type^} version MUST start with a digit [3-9]."
+	fi
+}
 
 # Check whether extension (module/theme) exists at drupal.org by requesting the
 # extension URL containing of the extension name.
-extension_url_exists() {
+drupal_extension_url_exists() {
 	local http_status="$(curl --location --output /dev/null --silent --head --fail -A $0 -w %{http_code} $http/$EXTENSION)"
 	say "Looking for '$EXTENSION' $extension_type..."
 
@@ -127,7 +135,7 @@ extension_url_exists() {
 # Check whether extension (module/theme) version exists at drupal.org by
 # requesting the archive (.tar.gz) filename containing of the extension name and
 # the version number.
-version_url_exists() {
+drupal_version_url_exists() {
 	local archive="$EXTENSION-$VERSION.tar.gz"
 	local ftp_status="$(curl --location --output /dev/null --silent --head --fail -A $0 -w %{http_code} $ftp/$archive)"
 	say "Looking for '$VERSION' version of '$EXTENSION' $extension_type..."
@@ -142,16 +150,190 @@ version_url_exists() {
 	fi
 }
 
+drupal_extension_file_get() {
+	local archive_file="$EXTENSION-$VERSION.tar.gz"
+
+	if [ ! -d $prefix ]; then
+		mkdir -p $prefix
+	fi
+
+	say "Downloading $archive_file..."
+	wget --directory-prefix=$prefix $ftp/$archive_file
+
+	say "Unpacking $archive_file..."
+	tar --directory=$prefix -xf $prefix/$archive_file
+
+	say "Removing $archive_file..."
+	rm $prefix/$archive_file
+
+	say "[OK]"
+}
+
 # GIT
 #
 # Custom git config file.
 config="$(git rev-parse --show-toplevel)/.drupal"
 
 # Current branch name.
-# If there are no commits yet (so there is no branch name available) set
-# 'master' as the current branch name.
-if ! $(git rev-parse --quiet --verify HEAD >/dev/null); then
-	branch="master"
-else
-	branch="$(git rev-parse --abbrev-ref HEAD)"
-fi
+branch="$(git status | grep -e '^On branch' | awk '{ print $3 }')"
+
+# This helper function checks wheter extension (module/theme) has been already
+# added. It returns only TRUE or FALSE because errors depend on commands, e.g.
+# the 'add' command returs error when the extension has been already added and
+# the 'move' command needs the extension to be already present in working tree.
+git_extension_exists() {
+	if [ "$(git config --file $config --get extension.$EXTENSION.name)" == "$EXTENSION" -o -d "$prefix/$EXTENSION" ]; then
+		return 0 # true
+	else
+		return 1 # false
+	fi
+}
+
+# Add extension (module/theme) to git config file (/.drupal), add new files to
+# index and commit changes.
+git_extension_add() {
+	git config --file $config --add extension.$EXTENSION.name "$EXTENSION"
+	git config --file $config --add extension.$EXTENSION.version "$VERSION"
+	git config --file $config --add extension.$EXTENSION.type "$extension_type"
+	git config --file $config --add extension.$EXTENSION.branch "$branch"
+	git config --file $config --add extension.$EXTENSION.prefix "$prefix"
+
+	git add $config $prefix/$EXTENSION
+
+	if [ -n "$message" ]; then
+		commit_message="$message"
+	else
+		commit_message="Add $extension_type '$EXTENSION' $VERSION"
+	fi
+
+	git commit $config $prefix/$EXTENSION -m "$commit_message"
+}
+
+# Update extension (module/theme) version in git config file (/.drupal), add new
+# files to index and commit changes.
+git_extension_update() {
+	git config --file $config extension.$EXTENSION.version "$VERSION"
+
+	git add $config $prefix/$EXTENSION
+
+	if [ -n "$message" ]; then
+		commit_message="$message"
+	else
+		commit_message="Update $extension_type '$EXTENSION' to $VERSION
+
+old version: $version_current
+new version: $VERSION"
+	fi
+
+	git commit $config $prefix/$EXTENSION -m "$commit_message"
+}
+
+# Update extension (module/theme) prefix in git config file (/.drupal) and
+# commit changes.
+git_extension_move() {
+	git config --file $config extension.$EXTENSION.prefix "$prefix"
+
+	git add $config $prefix_current/$EXTENSION $prefix/$EXTENSION
+
+	if [ -n "$message" ]; then
+		commit_message="$message"
+	else
+		commit_message="Move $extension_type '$EXTENSION'
+
+old path: $prefix_current
+new path: $prefix"
+	fi
+
+	git commit $config $prefix_current/$EXTENSION $prefix/$EXTENSION -m "$commit_message"
+}
+
+# Remove extension (module/theme) from git config file (/.drupal) and commit
+# changes.
+git_extension_remove() {
+	extension_type="$(git config --file $config --get extension.$EXTENSION.type)"
+	git config --file $config --remove-section extension.$EXTENSION
+
+	if [ -n "$message" ]; then
+		commit_message="$message"
+	else
+		commit_message="Remove $extension_type '$EXTENSION'"
+	fi
+
+	git add $config
+	git commit $config $prefix/$EXTENSION -m "$commit_message"
+}
+
+cmd_add() {
+	drupal_extension_name_validate $1
+	drupal_extension_version_validate $2
+
+	if git_extension_exists; then
+		die "'$EXTENSION' $extension_type already exists."
+	fi
+
+	requirements
+	drupal_extension_url_exists
+	drupal_version_url_exists
+	drupal_extension_file_get
+	git_extension_add
+}
+
+cmd_update() {
+	drupal_extension_name_validate $1
+	drupal_extension_version_validate $2
+	extension_type="$(git config --file $config --get extension.$EXTENSION.type)"
+	prefix="$(git config --file $config --get extension.$EXTENSION.prefix)"
+	version_current="$(git config --file $config --get extension.$EXTENSION.version)"
+
+	if git_extension_exists; then
+		if [ "$(git config --file $config --get extension.$EXTENSION.version)" == "$VERSION" ]; then
+			die "You have already the '$VERSION' of '$EXTENSION' $extension_type."
+		fi
+	else
+			die "'$EXTENSION' $extension_type does not exists."
+	fi
+
+	drupal_extension_url_exists
+	drupal_version_url_exists
+	requirements
+	drupal_extension_file_get
+	git_extension_update
+}
+
+cmd_move() {
+	drupal_extension_name_validate $1
+
+	if ! git_extension_exists; then
+		die "'$EXTENSION' $extension_type does not exists."
+	fi
+
+	local prefix_current="$(git config --file $config --get extension.$EXTENSION.prefix)"
+
+	if [ "$prefix_current" == "$prefix" ]; then
+		die "'$EXTENSION' $extension_type exists already within '$prefix'."
+	fi
+
+	if [ ! -d $prefix ]; then
+		mkdir -p $prefix
+	fi
+
+	mv $prefix_current/$EXTENSION $prefix/ || die "One or more files could not be moved!"
+
+	git_extension_move
+}
+
+cmd_remove() {
+	drupal_extension_name_validate $1
+
+	if ! git_extension_exists; then
+		die "'$EXTENSION' $extension_type does not exists."
+	fi
+
+	prefix="$(git config --file $config --get extension.$EXTENSION.prefix)"
+
+	rm -rf $prefix/$EXTENSION || die "One or more files could not be removed!"
+
+	git_extension_remove
+}
+
+"cmd_$command" "$@"
